#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
    /config/{logs,crontabs}

if [ ! -f "/config/tape.sh" ]; then
    echo "copying default tape script"
    cp /defaults/tape.sh /config/
else
    echo "using existing tape script"
fi

# permissions
chown -R abc:abc \
    /config
